<!DOCTYPE html>
<html>

<?php

$gegevens = array ("voornaam" => "Rayan", "Achternaam" => "Ouladomar", "Leeftijd" => "17", "klas" => "1D");
echo "Gegevens van Pijama:";
echo "<br>";
echo "Voornaam : ". $gegevens["voornaam"];
echo "<br>";
echo "Achternaam : ". $gegevens["Achternaam"];
echo "<br>";
echo "Leeftijd : " . $gegevens["Leeftijd"]. " jaar " ;
echo "<br>";
echo "Klas : ", $gegevens["klas"];
?>

</body>
</html>